# Generated by Django 5.2.14 on 2026-05-23 23:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shift_alter_student_shift'),
    ]

    def create_shift_from_old_code(apps, schema_editor):
        Shift = apps.get_model('core', 'Shift')
        Student = apps.get_model('core', 'Student')
        import datetime

        shift_map = {
            'turno1': ('TURNO 1', datetime.time(10, 0), datetime.time(12, 0)),
            'turno2': ('TURNO 2', datetime.time(12, 0), datetime.time(14, 0)),
            'turno3': ('TURNO 3', datetime.time(16, 30), datetime.time(18, 0)),
            'turno4': ('TURNO 4', datetime.time(18, 0), datetime.time(19, 30)),
            'turno5': ('TURNO 5', datetime.time(19, 30), datetime.time(21, 0)),
        }
        created_shifts = {}
        for student in Student.objects.all():
            old_shift = getattr(student, 'shift', None)
            if not old_shift:
                continue
            if old_shift not in created_shifts:
                name, start_time, end_time = shift_map.get(old_shift, (old_shift, datetime.time(0, 0), datetime.time(0, 0)))
                created_shifts[old_shift] = Shift.objects.create(
                    name=name,
                    start_time=start_time,
                    end_time=end_time,
                )
            student.shift = str(created_shifts[old_shift].pk)
            student.save(update_fields=['shift'])

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='code',
        ),
        migrations.AddField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.RunPython(create_shift_from_old_code, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='student',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.shift'),
        ),
    ]
