# Generated by Django 5.2.14 on 2026-05-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_shift_code_shift_end_time_shift_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
