# Generated by Django 5.2.14 on 2026-05-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_student_address_student_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dni',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
