# Generated by Django 5.2.14 on 2026-05-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_student_dni_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='membership_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de membresía'),
        ),
        migrations.AddField(
            model_name='student',
            name='membership_start',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de membresía'),
        ),
    ]
