# Generated by Django 5.2.14 on 2026-05-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_membership_and_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='active_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
