# Generated by Django 5.2.14 on 2026-06-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('category', models.CharField(max_length=200, verbose_name='Categoría')),
                ('size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=5, null=True, verbose_name='Talla')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['name'], 'verbose_name': 'Ciclo', 'verbose_name_plural': 'Ciclos'},
        ),
        migrations.AlterField(
            model_name='cycle',
            name='slug',
            field=models.SlugField(editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
