# Generated by Django 5.2.14 on 2026-07-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_revert_sale_original_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('yape', 'Yape'), ('plin', 'Plin'), ('otro', 'Otro')], default='efectivo', max_length=20, verbose_name='Método de pago'),
        ),
    ]
