# Generated by Django 5.2.14 on 2026-07-24 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_audit_trail'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado el'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado el'),
        ),
    ]
