# Generated by Django 5.2.14 on 2026-07-24 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_audit_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recibo emitido el'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_receipt_issued', to=settings.AUTH_USER_MODEL, verbose_name='Recibo emitido por'),
        ),
    ]
