# Generated by Django 5.2.14 on 2026-08-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_payment_receipt_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.CharField(blank=True, choices=[('camiseta_deportiva', 'Camiseta deportiva'), ('falda_short', 'Falda short'), ('short', 'Short'), ('medias', 'Medias'), ('rodilleras', 'Rodilleras'), ('mangas', 'Mangas'), ('poleras', 'Poleras')], max_length=40, null=True, verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='student',
            name='suffers_from',
            field=models.CharField(blank=True, help_text='Condición médica o alergia relevante', max_length=255, null=True, verbose_name='¿Sufre de algo?'),
        ),
    ]
